# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)

u1 = User.create(full_name: "Jerry Victor", username: "Jvictor", password: "victor" )
# # u2 = User.create(full_name: "", username: "", password: "" )
# # u3 = User.create(full_name: "", username: "", password: "" )

i1 = Item.create(company: "Apple", item_name: "Airpods Pro", price: 249.00, item_desc: "AirPods Pro have been designed to deliver Active Noise Cancellation for immersive sound, Transparency mode so you can hear your surroundings, and a customizable fit for all-day comfort. Just like AirPods, AirPods Pro connect magically to your Apple devices. And they’re ready to use right out of the case.", user_id: u1.id)
i2 = Item.create(company: "Apple", item_name: "MacBook Air" , price: 1199.00, item_desc: "Apple’s thinnest and lightest notebook gets supercharged with the Apple M1 chip. Tackle your projects with the blazing-fast 8-core CPU. Take graphics-intensive apps and games to the next level with the 7-core GPU. And accelerate machine learning tasks with the 16-core Neural Engine. All with a silent, fanless design and the longest battery life ever — up to 18 hours.¹ MacBook Air. Still perfectly portable. Just a lot more powerful.", user_id: u1.id)
i3 = Item.create(company: "Apple", item_name: "iPad Air" , price: 599.00, item_desc: "iPad Air features an all-screen design with a larger 10.9-inch Liquid Retina display, a new Touch ID sensor integrated into the top button, camera and audio upgrades, and debuts the powerful A14 Bionic, Apple's most powerful chip ever.", user_id: u1.id)
i4 = Item.create(company: "Bose", item_name: "Bose QuietComfort® 45 headphones" , price: 279.00, item_desc: "The minute you put on Bose QuietComfort 45 Wireless Noise Cancelling Headphones, you feel it — the iconic quiet that allows you to concentrate on your music or work on your passion projects. Plus, with these wireless headphones, you can experience the comfort and crystal-clear sound that can only come from Bose. The soft, plush cushions of these Bose wireless headphones seal you in. Then you flip the switch and whoosh — the world fades. The music starts. It’s love at first listen. The original Bluetooth headphones are back, now with a best-in-class combination of noise cancelling performance and premium comfort. Plus proprietary technology for deep, clear sound, and adjustable EQ so you can tune your music to your liking.", user_id: u1.id)
i5 = Item.create(company: "Bose", item_name: "SoundLink Revolve II Bluetooth® speaker" , price: 219.00, item_desc: "Meet SoundLink Revolve II, one of Bose best performing portable Bluetooth speakers yet. It delivers true 360° sound for consistent, uniform coverage. Place it in the center of the room and everyone gets the same experience. Or set it near a wall and sound will radiate and reflect around the room, immersing you. Taking it outdoors? Great, it’s meant to go where you go", user_id: u1.id)
i6 = Item.create(company: "Bose", item_name: "Bose Smart Speaker 500" , price: 349.00, item_desc: "It’s powerfully simple. Fill any room with wall-to-wall stereo sound, while built-in voice control puts millions of songs at the tip of your tongue.", user_id: u1.id)
# # i7 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i8 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i9 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i10 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i11 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i12 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i13 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i14 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i15 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i16 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i17 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i18 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i19 = Item.create(company: "", item_name: "" , price: , item_desc: "" )
# # i20 = Item.create(company: "", item_name: "" , price: , item_desc: "" )

p1 = Image.create(url: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1591634795000", item_id: i1.id)
p2 = Image.create(url: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-config-20220606?wid=410&hei=249&fmt=jpeg&qlt=95&.v=1654122880566", item_id: i2.id)
p3 = Image.create(url: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-202203?wid=1765&hei=2000&fmt=jpeg&qlt=95&.v=1645665079887", item_id: i3.id)
p4 = Image.create(url: "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc45/product_silo_images/QC45_PDP_Ecom-Gallery-B02.png/jcr:content/renditions/cq5dam.web.600.600.png", item_id: i4.id)
p5 = Image.create(url: "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/speakers/soundlink_revolve_ii/product_silo_images/soundlink_revolve_lux_gray_EC_01.psd/jcr:content/renditions/cq5dam.web.600.600.png", item_id: i5.id)
p6 = Image.create(url: "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/bose_home_speaker_500/product_silo_images/bose_home_speaker_500_luxe_silver_vpa_alexa_EC_hero.psd/jcr:content/renditions/cq5dam.web.600.600.png", item_id: i6.id)
# # p7 = Image.create(url: "", item_id: "")
# # p8 = Image.create(url: "", item_id: "")
# # p9 = Image.create(url: "", item_id: "")
# # p10 = Image.create(url: "", item_id: "")
# # p11 = Image.create(url: "", item_id: "")
# # p12 = Image.create(url: "", item_id: "")
# # p13 = Image.create(url: "", item_id: "")
# # p14 = Image.create(url: "", item_id: "")
# # p15 = Image.create(url: "", item_id: "")
# # p16 = Image.create(url: "", item_id: "")
# # p17 = Image.create(url: "", item_id: "")
# # p18 = Image.create(url: "", item_id: "")
# # p19 = Image.create(url: "", item_id: "")
# # p20 = Image.create(url: "", item_id: "")

r1 = Rating.create(rating: 4.3, item_id: i1.id, user_id: u1.id)
r2 = Rating.create(rating: 5, item_id: i2.id, user_id: u1.id)
r3 = Rating.create(rating: 5, item_id: i3.id, user_id: u1.id)
r4 = Rating.create(rating: 4.5, item_id: i4.id, user_id: u1.id)
r5 = Rating.create(rating: 4.7, item_id: i5.id, user_id: u1.id)
r6 = Rating.create(rating: 3.9, item_id: i6.id, user_id: u1.id)
# # r7 = Rating.create(rating: , item_id: , user_id: )
# # r8 = Rating.create(rating: , item_id: , user_id: )
# # r9 = Rating.create(rating: , item_id: , user_id: )
# # r10 = Rating.create(rating: , item_id: , user_id: )
# # r11 = Rating.create(rating: , item_id: , user_id: )
# # r12 = Rating.create(rating: , item_id: , user_id: )
# # r13 = Rating.create(rating: , item_id: , user_id: )
# # r14 = Rating.create(rating: , item_id: , user_id: )
# # r15 = Rating.create(rating: , item_id: , user_id: )
# # r16 = Rating.create(rating: , item_id: , user_id: )
# # r17 = Rating.create(rating: , item_id: , user_id: )
# # r18 = Rating.create(rating: , item_id: , user_id: )
# # r19 = Rating.create(rating: , item_id: , user_id: )
# # r20 = Rating.create(rating: , item_id: , user_id: )

rev1 = Review.create(post: "I got these as an upgrade from the first Airpods and I love these so much! They are extremely comfortable with the rubber things that sit in your ear. I also work out and go on runs with these and never have had any issues with them falling out! Definitely recommend. I do keep mine in a case to tell them apart from others and also protect them. 
(I even gifted these to my mom and she loves them as well)", item_id: i1.id, user_id: u1.id)
rev2 = Review.create(post: "I have been using this laptop as my daily driver ever since the day I purchased it. It has never overheated. The most it ever gets is a bit warm after having 10+ windows and applications open in the background. The feeling of the laptop is therapeutic and feels amazing, but I recommend having some form of protection because it does feel like one drop from a decent height can be fatal. The display is great. The sound is from the speakers are actually more than decent. Overall, this MacBook Air has been amazing. Highly recommend!", item_id: i2.id , user_id: u1.id)
rev3 = Review.create(post: "Completely changed my life as an artist. With the procreate app and the long battery life, my artwork continues to improve day by day. Blows every single drawing tablet out of the water. Being an android customer, I was weary about an apple. But it was the best creative decision I have ever made.", item_id: i3.id, user_id: u1.id)
rev4 = Review.create(post: "I previously had a pair of Bose noise cancelling headphones that I lost & I have purchased another pair due to neighbor's loud tv & music. It has made a huge difference in my peace zone.", item_id: i4.id, user_id: u1.id)
rev5 = Review.create(post: "Great features! I was tired of plugging into speakers and am glad I found this wireless speaker.", item_id: i5.id, user_id: u1.id)
rev6 = Review.create(post: "This Bose 500 is everything!! Best best purchase!! Sound is crystal clean and flows perfectly throughout my house!!", item_id: i6.id, user_id: u1.id)
# # rev7 = Review.create(post: "", item_id: , user_id: )
# # rev8 = Review.create(post: "", item_id: , user_id: )
# # rev9 = Review.create(post: "", item_id: , user_id: )
# # rev10 = Review.create(post: "", item_id: , user_id: )
# # rev11 = Review.create(post: "", item_id: , user_id: )
# # rev12 = Review.create(post: "", item_id: , user_id: )
# # rev13 = Review.create(post: "", item_id: , user_id: )
# # rev14 = Review.create(post: "", item_id: , user_id: )
# # rev15 = Review.create(post: "", item_id: , user_id: )
# # rev16 = Review.create(post: "", item_id: , user_id: )
# # rev17 = Review.create(post: "", item_id: , user_id: )
# # rev18 = Review.create(post: "", item_id: , user_id: )
# # rev19 = Review.create(post: "", item_id: , user_id: )
# # rev20 = Review.create(post: "", item_id: , user_id: )


puts "Done Seeding!"